version: '3.3'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - API_URL="VITE_API_BASE_URL"
    container_name: vendetta-frontend
    ports:
      - '5000:5000'
    networks:
      - vendetta-network
volumes:
  postgresDB:
networks:
  vendetta-network:
    driver: bridge
    external: true
