version: '3.1'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - API_URL="$PORT"
    container_name: vendetta-frontend
    ports:
      - '5000:5000'
volumes:
  postgresDB:
